set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage itself
Plugin 'VundleVim/Vundle.vim'

" Put bundles here

Plugin 'tomasr/molokai'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'bling/vim-airline'
Plugin 'tmhedberg/matchit'
Plugin 'airblade/vim-gitgutter'
Plugin 'Valloric/YouCompleteMe'
Plugin 'SirVer/ultisnips'
Plugin 'scrooloose/syntastic'
Plugin 'jpalardy/vim-slime'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'ervandew/supertab'

" Bundles go above this!
call vundle#end()
filetype plugin indent on
set modelines=0

syntax on
set laststatus=2
colorscheme molokai

" Powerline provides mode indicator
set noshowmode

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set shiftround

set encoding=utf-8
set scrolloff=5
set autoindent
set showcmd
set hidden
set visualbell
set cursorline
set ttyfast
set number

let mapleader = ","
let localleader = "\\"

" Better search and replace
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

" Esc is hard to reach, and CAPs is my hyper
inoremap jk <ESC>
inoremap <ESC> <nop>

" Edit vimrc faster
nnoremap <leader>ev :e $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" 0 and $ are hard to reach. G and gg don't need duplication
nnoremap H 0
nnoremap L $

" Better split navigation
nnoremap <C-H> <C-W><C-H>
nnoremap <C-L> <C-W><C-L>
 
" Airline Config
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme='molokai'
let g:airline#extensions#tabline#enabled = 1

" YouCompleteMe Config
let g:ycm_path_to_python_interpreter = '/usr/local/bin/python'
set completeopt-=preview
let g:ycm_add_preview_to_completeopt = 0

" YCM + Ultisnips + Supertab
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

" Syntastic config
let g:syntastic_error_symbol = 'X'
let g:syntastic_warning_symbol = '!'
let g:syntastic_style_error_symbol = 'X'
let g:syntastic_style_warning_label = '!'
let g:syntastic_check_on_open = 1

" Vim-Slime config
let g:slime_target = 'tmux'
let g:slime_python_ipython = 1
