set nocompatible
runtime bundle/vim-pathogen/autoload/pathogen.vim
filetype off
execute pathogen#infect()
filetype plugin indent on
set modelines=0

syntax on
colorscheme molokai

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set encoding=utf-8
set scrolloff=5
set autoindent
set showmode
set showcmd
set hidden
set visualbell
set cursorline
set ttyfast
set number

let mapleader = ","

set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set colorcolumn=79

inoremap jj <ESC>
