# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
export WORKON_HOME=$HOME/VirtualEnvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
source /usr/local/bin/virtualenvwrapper.sh

alias ls="ls -laG "

export VISUAL=vim
export EDITOR="$VISUAL"
export PATH=/usr/local/bin:$PATH
export JAVA_HOME=$(/usr/libexec/java_home)

export GITHUB_USER='micahsaul'

alias rexster-start="~/Projects/tools/rexster/rexster-server/bin/rexster.sh --start -c ~/Projects/tools/rexster/rexster-server/config/rexster.xml"

alias rexster-stop="~/Projects/tools/rexster/rexster-server/bin/rexster.sh --stop"

alias mou="open ~/Applications/Mou.app"

eval "$(hub alias -s)"
VIRTUAL_ENV_DISABLE_PROMPT=yes
source /usr/local/Cellar/todo-txt/2.10/etc/bash_completion.d/todo_completion complete -F _todo t
alias t='/usr/local/Cellar/todo-txt/2.10/bin/todo.sh -d ~/todo/todo.cfg'
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
